fix: adjust permissions on safe-settings working dir
github/safe-settings pull request #384
Opened 2023-01-24 08:27 UTC by martinm82

Fixes #362

2023-02-14 10:51 UTC, martinm82 commented
@decyjphr could you please have a look at this PR. Thanks

2023-02-14 19:46 UTC, decyjphr commented on Dockerfile
>  WORKDIR /opt/safe-settings
Yes, this should be enough to create the /op/safe-settings dir. We don't need to explicitly create it like in the previous version.

2023-02-14 19:46 UTC, decyjphr approved these changes
👍🏾

2023-02-24 02:32 UTC, quike approved these changes

2023-03-29 15:04 UTC, freef4ll commented
Would be good to have these merged, as also running into permission issue after an upgrade.

2023-03-29 15:32 UTC, decyjphr commented
@martinm82 can we make these changes? Apologies if you have already made those...
```dockerfile
FROM node:14.17.6-alpine
WORKDIR /opt/safe-settings
ENV NODE_ENV production
## Set the Labels
LABEL version="1.0" \
      description="Probot app which is a modified version of Settings Probot GitHub App" \
      maintainer="GitHub Professional Services <services@github.com>"

## These files are copied separately to allow updates
## to the image to be as small as possible
COPY  package.json /opt/safe-settings/
COPY  index.js /opt/safe-settings/
COPY  lib /opt/safe-settings/lib

## Install the app and dependencies
RUN npm install

## This app will listen on port 3000
EXPOSE 3000

USER node

## This does not start properly when using the ['npm','start'] format
## so stick with just calling it outright
CMD npm start
```

2023-04-03 11:44 UTC, martinm82 commented
> @martinm82 can we make these changes? Apologies if you have already made those...
> 
> ```dockerfile
> FROM node:14.17.6-alpine
> WORKDIR /opt/safe-settings
> ENV NODE_ENV production
> ## Set the Labels
> LABEL version="1.0" \
>       description="Probot app which is a modified version of Settings Probot GitHub App" \
>       maintainer="GitHub Professional Services <services@github.com>"
> 
> ## These files are copied separately to allow updates
> ## to the image to be as small as possible
> COPY  package.json /opt/safe-settings/
> COPY  index.js /opt/safe-settings/
> COPY  lib /opt/safe-settings/lib
> 
> ## Install the app and dependencies
> RUN npm install
> 
> ## This app will listen on port 3000
> EXPOSE 3000
> 
> USER node
> 
> ## This does not start properly when using the ['npm','start'] format
> ## so stick with just calling it outright
> CMD npm start
> ```

Sorry that it took so long. Yes, moving workdir to top seems to solve the issue. Thanks @decyjphr for the better solution.

2023-04-03 19:01 UTC, decyjphr requested changes

2023-04-03 19:01 UTC, decyjphr commented on Dockerfile
> +RUN   mkdir /opt/safe-settings \
@martinm82 could we make the Dockerfile simpler as follows:
```dockerfile
FROM node:14.17.6-alpine
WORKDIR /opt/safe-settings
ENV NODE_ENV production
## Set the Labels
LABEL version="1.0" \
      description="Probot app which is a modified version of Settings Probot GitHub App" \
      maintainer="GitHub Professional Services <services@github.com>"

## These files are copied separately to allow updates
## to the image to be as small as possible
COPY  package.json /opt/safe-settings/
COPY  index.js /opt/safe-settings/
COPY  lib /opt/safe-settings/lib

## Install the app and dependencies
RUN npm install

## This app will listen on port 3000
EXPOSE 3000

USER node

## This does not start properly when using the ['npm','start'] format
## so stick with just calling it outright
CMD npm start
```

2023-04-03 19:01 UTC, decyjphr commented on Dockerfile
> +RUN   mkdir /opt/safe-settings \
@martinm82 let me know if this above change would work for you. I am not sure why the previous docker file had python install, etc. I don't believe it needs to be that complex.

Probably, we can take this opportunity and update the node version to 18

2023-04-03 19:01 UTC, decyjphr commented on Dockerfile
>  RUN apk add --no-cache make python
We don't need to run install python any more. So these 2 lines can be removed. It'll make the Dockerfile simpler

2023-04-05 00:06 UTC, robandpdx commented
@martinm82 @decyjphr I have create #453 to supercede this PR. I've test the container and it seems to be working fine.

2023-04-05 12:09 UTC, martinm82 commented
Closing in favour of https://github.com/github/safe-settings/pull/453

2023-04-05 12:09 UTC, closed without merging